# Generated by Django 4.2.2 on 2023-09-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaminghubwebsiteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='your_profile',
            name='date_birth',
            field=models.CharField(default=None, max_length=70),
        ),
    ]
