# Generated by Django 4.2.2 on 2023-09-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaminghubwebsiteapp', '0002_alter_your_profile_date_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='your_profile',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='your_profile',
            name='image',
            field=models.FileField(default=None, upload_to='static/'),
        ),
    ]
