# Generated by Django 4.2.2 on 2023-09-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaminghubwebsiteapp', '0003_your_profile_active_alter_your_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='otp_verify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=40)),
                ('otp', models.CharField(default=None, max_length=6)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
