# Generated by Django 4.2.2 on 2023-09-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaminghubwebsiteapp', '0004_otp_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='your_profile',
            name='image',
            field=models.FileField(default=None, upload_to='static/user_photo'),
        ),
    ]
