# Generated by Django 4.2.2 on 2023-09-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaminghubwebsiteapp', '0008_remove_otp_verify_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='your_profile',
            name='con',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
