# Generated by Django 4.2.2 on 2023-09-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaminghubwebsiteapp', '0010_image_mod_remove_your_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='game_scheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(default=None, max_length=90)),
                ('game', models.CharField(default=None, max_length=200)),
                ('schedule_date', models.DateField(default=None, max_length=12)),
                ('schedule_time', models.TimeField(default=None, max_length=120)),
            ],
        ),
    ]
