# Generated by Django 4.2.2 on 2023-09-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaminghubwebsiteapp', '0011_game_scheduler'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_scheduler',
            name='email',
            field=models.EmailField(default=None, max_length=90),
        ),
        migrations.AddField(
            model_name='game_scheduler',
            name='name',
            field=models.CharField(default=None, max_length=90),
        ),
        migrations.AddField(
            model_name='game_scheduler',
            name='phone',
            field=models.BigIntegerField(default=None),
        ),
    ]
