# Generated by Django 4.2.2 on 2023-09-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaminghubwebsiteapp', '0012_game_scheduler_email_game_scheduler_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp_verify',
            name='name',
            field=models.CharField(default=None, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='otp_verify',
            name='otp',
            field=models.CharField(default=None, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='your_profile',
            name='name',
            field=models.CharField(default=None, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='your_profile',
            name='phone',
            field=models.BigIntegerField(default=None, unique=True),
        ),
    ]
